import { NextResponse } from 'next/server'
import prisma from '@/lib/prisma'

export async function GET() {
  try {
    const [
      traditions,
      teachings,
      misconceptions,
      sacredTexts,
      peaceInitiatives,
      movementMembers,
      newsletterSubscribers,
      assessmentResults,
      shareableQuotes,
      similarityThemes,
      users,
      roleRequests,
      corePillars,
      aboutContent,
      aboutValues,
      aboutLeaders,
      missionContent,
      wisdomToAction,
      impactGoals,
      featuredPrograms,
      regionalInitiatives,
      getInvolved,
      currentInitiatives,
      teachingSections,
      truthSections,
      traditionSections,
      sufiContent,
      approachContent,
      sufiCards,
      approachCards,
      similarityTeachings,
      pageContent,
      founderSections,
    ] = await Promise.all([
      prisma.tradition.count(),
      prisma.teaching.count(),
      prisma.misconception.count(),
      prisma.sacredText.count(),
      prisma.peaceInitiative.count(),
      prisma.movementMember.count(),
      prisma.newsletterSubscriber.count(),
      prisma.assessmentResult.count(),
      prisma.shareableQuote.count(),
      prisma.similarityTheme.count(),
      prisma.user.count(),
      prisma.roleRequest.count({ where: { status: 'pending' } }),
      prisma.corePillar.count(),
      prisma.aboutContent.count(),
      prisma.aboutValue.count(),
      prisma.aboutLeader.count(),
      prisma.missionContent.count(),
      prisma.wisdomToAction.count(),
      prisma.impactGoal.count(),
      prisma.featuredProgram.count(),
      prisma.regionalInitiative.count(),
      prisma.getInvolved.count(),
      prisma.currentInitiative.count(),
      prisma.teachingSection.count(),
      prisma.truthSection.count(),
      prisma.traditionSection.count(),
      prisma.sufiContent.count(),
      prisma.approachContent.count(),
      prisma.sufiCard.count(),
      prisma.approachCard.count(),
      prisma.similarityTeaching.count(),
      prisma.pageContent.count(),
      prisma.founderPageSection.count(),
    ])

    return NextResponse.json({
      traditions,
      teachings,
      misconceptions,
      sacredTexts,
      peaceInitiatives,
      movementMembers,
      newsletterSubscribers,
      assessmentResults,
      shareableQuotes,
      similarityThemes,
      users,
      roleRequests,
      corePillars,
      aboutContent,
      aboutValues,
      aboutLeaders,
      missionContent,
      wisdomToAction,
      impactGoals,
      featuredPrograms,
      regionalInitiatives,
      getInvolved,
      currentInitiatives,
      teachingSections,
      truthSections,
      traditionSections,
      sufiContent,
      approachContent,
      sufiCards,
      approachCards,
      similarityTeachings,
      pageContent,
      founderSections,
    })
  } catch (error) {
    console.error('Error fetching admin stats:', error)
    return NextResponse.json(
      { error: 'Failed to fetch stats' },
      { status: 500 }
    )
  }
}
